### ISSUE TITLE
Page doesn't load

### ISSUE THREAD

**Issue by Michael-E-Rose** [uclab-potsdam/scienceforukraine#12]
Someone tried to load page https://scienceforukraine.eu/d/U1585 and for 60 seconds straight nothing happend. He's using Safari and Firefox on a Mac.

For me it takes about 1 second: First I see the frames and headers, then the rest builds up.

**Comment by Michael-E-Rose** [comment]
He reports that the main page [https://scienceforukraine.eu](https://scienceforukraine.eu/) doesn't display any offers at all.

**Comment by fidelthomet** [comment]
Can you provide more details like browser and os versions?

**Comment by Michael-E-Rose** [comment]
I inquired with the person but according to his OOO reply he's on holiday till August 19th

**Comment by fidelthomet** [comment]
Ok let's wait and see. I'm on a mac myself and don't have an issues in these browsers. Might have only been a temporary issue with reaching the data server

**Comment by fidelthomet** [comment]
Closing this, please reopen in case of any updates
