### ISSUE TITLE
events merge together on the starting page

### ISSUE THREAD

**Issue by sanitareins** [uclab-potsdam/scienceforukraine#15]
On the starting page, there is a small bug: when there are 2 events in one day, they merge together. 
<img width="659" alt="image (3)" src="https://user-images.githubusercontent.com/17168457/184378464-5b5c683a-b7d6-4d9e-b0ce-46eba9136d91.png">

**Comment by fidelthomet** [comment]
Hm, I don't really get the issue. The events listed there come from this [markdown file](https://github.com/uclab-potsdam/scienceforukraine/blob/main/public/pages/home-events.md), can you not update this in there?
