### ISSUE TITLE
Remote filter does not return entries 

### ISSUE THREAD

**Issue by hjalmberi** [uclab-potsdam/scienceforukraine#24]
The Google Sheets file has active remote listings, but a toggle at the website returns an empty page. Could you fix it so that the entries are shown? Thanks a lot!
![IMG_3621](https://github.com/uclab-potsdam/scienceforukraine/assets/3543515/a585fbb6-d0e5-4915-bcac-df672a08e185)

A similar Accommodation toggle works just fine

**Comment by Michael-E-Rose** [comment]
This was acutally an easy fix: The column name in the sour spreadsheet was wrong. It was named "Remote work", but it should be "Remote". I didn't see it because of the word wrap.

Now everything is in order :)
